kind: Service
apiVersion: v1
metadata:
  name: csi-zfssnapshotter
  labels:
    app: csi-zfssnapshotter
spec:
  selector:
    app: csi-zfssnapshotter
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-zfssnapshotter
spec:
  serviceName: "csi-zfssnapshotter"
  replicas: 1
  selector:
    matchLabels:
      app: csi-zfssnapshotter
  template:
    metadata:
      labels:
        app: csi-zfssnapshotter
    spec:
      serviceAccount: csi-snapshotter
      containers:
        - name: csi-snapshotter
          # TODO: change to official image when released
          image: quay.io/k8scsi/csi-snapshotter:v2.0.0-rc2
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-zfs
            type: DirectoryOrCreate
          name: socket-dir
