kind: Service
apiVersion: v1
metadata:
  name: csi-zfsprovisioner 
  labels:
    app: csi-zfsprovisioner 
spec:
  selector:
    app: csi-zfsprovisioner 
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-zfsprovisioner
spec:
  serviceName: "csi-zfsprovisioner"
  replicas: 1
  selector:
    matchLabels:
      app: csi-zfsprovisioner
  template:
    metadata:
      labels:
        app: csi-zfsprovisioner
    spec:
      serviceAccountName: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.5.0-rc1
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-zfs
            type: DirectoryOrCreate
          name: socket-dir
