kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-raw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-zfs-sc
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
