/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	zfsvolumev1 "github.com/maxaudron/zfs-csi-driver/pkg/apis/zfsvolume/v1"
	versioned "github.com/maxaudron/zfs-csi-driver/pkg/client/clientset/versioned"
	internalinterfaces "github.com/maxaudron/zfs-csi-driver/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/maxaudron/zfs-csi-driver/pkg/client/listers/zfsvolume/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ZFSVolumeInformer provides access to a shared informer and lister for
// ZFSVolumes.
type ZFSVolumeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ZFSVolumeLister
}

type zFSVolumeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewZFSVolumeInformer constructs a new informer for ZFSVolume type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewZFSVolumeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredZFSVolumeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredZFSVolumeInformer constructs a new informer for ZFSVolume type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredZFSVolumeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZfsV1().ZFSVolumes(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZfsV1().ZFSVolumes(namespace).Watch(options)
			},
		},
		&zfsvolumev1.ZFSVolume{},
		resyncPeriod,
		indexers,
	)
}

func (f *zFSVolumeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredZFSVolumeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *zFSVolumeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&zfsvolumev1.ZFSVolume{}, f.defaultInformer)
}

func (f *zFSVolumeInformer) Lister() v1.ZFSVolumeLister {
	return v1.NewZFSVolumeLister(f.Informer().GetIndexer())
}
